apiVersion: apps/v1
kind: Deployment
metadata:
  name: apuestas-predictor
  namespace: apuestas
  labels:
    app: apuestas-predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apuestas-predictor
  template:
    metadata:
      labels:
        app: apuestas-predictor
    spec:
      # ← Aquí indicas el Secret para image pull
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: apuestas-predictor
        image: ghcr.io/chemavx-git/apuestas-predictor:latest
        # tus puertos/envFrom, etc.
