apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  namespace: apuestas
  labels:
    app: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: ingestion
        image: ghcr.io/chemavx-git/ingestion:latest
        envFrom:
        - secretRef:
            name: ingestion-env
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: apuestas
spec:
  selector:
    app: ingestion
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
