apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  labels:
    app: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
      - name: ingestion
        image: ghcr.io/${{ github.repository_owner }}/ingestion:latest
        envFrom:
        - secretRef:
            name: ingestion-env
        # no exponemos puertos HTTP internos
        restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
spec:
  selector:
    app: ingestion
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
